= FeedSpool =

Simplified syndication feed poller and spooler written in Python.

== Background ==

The basic idea of FeedSpool is to handle many of the up-front details of 
syndication feed aggregation, while being as stupid as possible about the
feeds themselves.  What this means is that FeedSpool can take care of things
such as subscription management, feed poll scheduling, feed data fetching 
and caching, even tracking new feed entries-- all while turning as blind an
eye as possible to feed formats and payloads.

Furthermore, the goal of FeedSpool is to be as integration and tweak 
friendly as possible.  Toward this goal, the attempt will be made to make
data generated by this system easily accessible by tools not necessarily
written in Python or using FeedSpool modules.  So, all of the formats and
things persisted by this system should be both readable and writeable in 
standard formats found in other languages and platforms.

And one last thing:  In order to make this thing easy to get up and running,
you shouldn't need to install anything other than Python and this package.
Dependency on non-core Python modules will be avoided as much as possible.

  * Subscription management
  * Poll scheduling
  * Conditional HTTP GET
  * Feed data caching (via HTTPCache?)
  * Entry spools from sliced up feeds

